# Generated by Django 4.1.7 on 2023-02-17 17:53

from django.db import migrations, models
import django.db.models.deletion
import white_whale.albums.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('file', models.FileField(upload_to=white_whale.albums.models.user_directory_path)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ww_albums.album')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
